<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>CountTogether.MacroDeckPlugin</RootNamespace>
    <TargetFramework>net8.0-windows10.0.22000</TargetFramework>
    <Nullable>enable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<Authors>CountTogether</Authors>
	<Company>CountTogether</Company>
	<Version>1.0.1</Version>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<Platforms>AnyCPU;x64</Platforms>
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CountTogether.PublicApiSdk" Version="1.0.1" />
    <PackageReference Include="SuchByte.MacroDeck" Version="2.14.1" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy /Y &quot;$(TargetDir)$(TargetName).dll&quot; &quot;C:\Users\suchb\AppData\Roaming\Macro Deck\plugins\CountTogether.MacroDeckPlugin\$(TargetName).dll&quot;" />
	</Target>

</Project>
